import { DemoIncident } from '../db/schema';

export const DEMO_INCIDENTS: DemoIncident[] = [
  {
    id: 'INC-001',
    title: 'Payment API Latency Spike',
    service: 'payment-service',
    environment: 'production',
    severity: 'critical',
    description: 'Payment API response times spiked to 8000ms (p99). Users unable to complete checkout. Alert triggered at 14:32 UTC. Error rate increased to 23%. Downstream services timing out waiting for payment confirmation.',
    errorMessage: 'TimeoutError: Connection pool exhausted after 30000ms. No connections available. Pool size: 10, waiting: 47',
    logs: '[14:32:01] WARN Pool utilization at 100%\n[14:32:15] ERROR Connection timeout - pool exhausted\n[14:32:15] ERROR 47 requests waiting for connection\n[14:32:30] CRITICAL Payment API p99 latency: 8234ms\n[14:32:45] ERROR Downstream checkout-service timeout',
    status: 'resolved',
    rootCause: 'Database connection pool exhaustion caused by a surge in payment traffic combined with a slow query introduced in the previous deployment that held connections for 10x longer than normal.',
    resolution: 'Increased connection pool size from 10 to 50, optimized the slow query with proper indexing, and added connection timeout of 5000ms with automatic retry.',
    resolutionTimeMinutes: 11,
    failedApproaches: 'Restarting payment service pods (did not help as root cause was DB pool). Scaling horizontally (worsened pool contention). Disabling query cache (no effect).',
    outcome: 'Payment API latency returned to normal (<200ms p99). Connection pool utilization stabilized at 40% under peak load. Zero payment failures after fix.',
    engineerFeedback: 'Should have had connection pool monitoring. Added alerts for >80% pool utilization. Added connection timeout to prevent indefinite waiting.',
    createdAt: '2024-01-15T14:32:00Z',
    resolvedAt: '2024-01-15T14:43:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-002',
    title: 'Auth Service Complete Outage',
    service: 'auth-service',
    environment: 'production',
    severity: 'critical',
    description: 'Auth service stopped accepting requests after emergency JWT secret rotation. All users logged out simultaneously. Login attempts returning 401 for all users. 100% error rate on /api/auth/* endpoints.',
    errorMessage: 'JsonWebTokenError: invalid signature. All existing tokens invalidated after secret rotation without session migration.',
    logs: '[09:15:00] INFO JWT secret rotation initiated\n[09:15:02] ERROR JsonWebTokenError: invalid signature\n[09:15:02] ERROR 100% auth failure rate\n[09:15:10] CRITICAL Auth service: 0% success rate\n[09:15:15] ERROR All active sessions invalidated',
    status: 'resolved',
    rootCause: 'JWT secret rotation was performed without a grace period for existing tokens. New secret was applied immediately, invalidating all active user sessions simultaneously.',
    resolution: 'Implemented dual-secret validation: accept both old and new secrets for 15-minute overlap period. Rotated to new secret with graceful migration. Added runbook for safe JWT rotation.',
    resolutionTimeMinutes: 23,
    failedApproaches: 'Rolling back the secret rotation (not possible due to security requirements). Issuing blanket token refresh (failed because validation was broken). Restarting auth service pods (had no effect).',
    outcome: 'Auth service restored with 99.9% success rate. Implemented proper secret rotation procedure with overlap period. Zero data loss. All users able to re-login successfully.',
    engineerFeedback: 'Critical: Never rotate JWT secrets without overlap period. Created runbook with exact steps for safe rotation including 15-minute dual-validation window.',
    createdAt: '2024-01-22T09:15:00Z',
    resolvedAt: '2024-01-22T09:38:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-003',
    title: 'Redis Cache Layer Failure',
    service: 'cache-service',
    environment: 'production',
    severity: 'high',
    description: 'Redis cache hit rate dropped from 94% to 0% causing severe database load. API response times increased 10x. Database CPU at 98%. Cache service reporting OOM errors and evicting all keys.',
    errorMessage: 'OOMKilled: Redis container exceeded memory limit of 2Gi. maxmemory-policy: allkeys-lru. All keys evicted.',
    logs: '[11:45:00] WARN Redis memory usage: 95%\n[11:45:30] ERROR Redis OOM: evicting keys\n[11:45:31] CRITICAL Cache hit rate: 0%\n[11:45:31] CRITICAL DB CPU: 98%\n[11:46:00] ERROR Redis connection refused - restarting',
    status: 'resolved',
    rootCause: 'Redis memory limit was set too low for the current data volume. A marketing campaign caused 3x more unique users than normal, filling the cache. The allkeys-lru eviction policy then removed all keys including critical session data.',
    resolution: 'Increased Redis memory limit from 2GB to 8GB. Changed eviction policy to volatile-lru (only evict keys with TTL). Added memory usage alerts at 80% threshold.',
    resolutionTimeMinutes: 8,
    failedApproaches: 'Restarting Redis (keys lost, cold cache). Reducing TTL values (cache miss storm). Disabling caching for some services (increased DB load further).',
    outcome: 'Cache hit rate restored to 96%. Database CPU stabilized at 25%. Added capacity planning for traffic spikes.',
    engineerFeedback: 'Memory limits should scale with expected traffic. volatile-lru is safer than allkeys-lru for mixed workloads. Cache warming strategy needed for cold starts.',
    createdAt: '2024-02-03T11:45:00Z',
    resolvedAt: '2024-02-03T11:53:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-004',
    title: 'Database Connection Pool Exhaustion',
    service: 'user-service',
    environment: 'production',
    severity: 'high',
    description: 'User service database connections exhausted during peak traffic. New user registrations failing. Profile update requests timing out. Connection pool maxed at 20 connections, 300+ requests queued.',
    errorMessage: 'PoolError: Cannot acquire connection. Pool is at capacity (20/20). Queued: 312. Wait timeout: 30000ms exceeded.',
    logs: '[16:20:00] WARN DB pool: 18/20 connections active\n[16:20:30] ERROR DB pool: 20/20 at capacity\n[16:20:31] ERROR 312 requests queued for DB connection\n[16:21:00] ERROR Pool wait timeout exceeded\n[16:21:00] CRITICAL User registration: 0% success',
    status: 'resolved',
    rootCause: 'Database connection pool size was not increased when user service was scaled to 10 replicas. Each replica had pool size 20, but DB max_connections was only 100. Pool exhaustion under normal load after scaling.',
    resolution: 'Reduced pool size per replica to 8 (total: 80 connections, leaving headroom). Added PgBouncer connection pooler between services and DB. Increased DB max_connections to 200.',
    resolutionTimeMinutes: 14,
    failedApproaches: 'Increasing pool size (worsened DB overload). Restarting service replicas (temporary relief, issue returned). Adding read replicas (registration writes still hitting primary).',
    outcome: 'User service operating normally with PgBouncer. Can now handle 5x traffic without connection issues. DB connection count stable.',
    engineerFeedback: 'Always use a connection pooler in front of Postgres in multi-replica deployments. Pool size × replicas must be < DB max_connections.',
    createdAt: '2024-02-10T16:20:00Z',
    resolvedAt: '2024-02-10T16:34:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-005',
    title: 'Failed Deployment - Config Error',
    service: 'order-service',
    environment: 'production',
    severity: 'high',
    description: 'Order service deployment failed due to missing environment variable. New pods in CrashLoopBackOff. Order creation returning 503. Deployment rolled out to 100% of pods before failure detected.',
    errorMessage: 'Error: Required environment variable DATABASE_URL is not set. Cannot start application. Exiting with code 1.',
    logs: '[10:00:00] INFO Deployment order-service:v2.3.1 started\n[10:00:30] INFO Pod order-service-new-1: Running\n[10:00:35] ERROR DATABASE_URL not found in environment\n[10:00:35] ERROR Process exiting: missing required config\n[10:00:36] ERROR Pod order-service-new-1: CrashLoopBackOff',
    status: 'resolved',
    rootCause: 'New deployment config referenced a Kubernetes secret that was not created in the production namespace. The secret existed in staging but was missed during production deployment checklist.',
    resolution: 'Immediately rolled back to v2.3.0 using kubectl rollout undo. Created missing secret in production namespace. Re-deployed v2.3.1 successfully.',
    resolutionTimeMinutes: 6,
    failedApproaches: 'Manually patching the deployment env (kubectl apply was slow). Trying to set env var directly on running pods (not supported after crash). Forward-deploying a hotfix (too risky).',
    outcome: 'Order service restored to full operation in 6 minutes via rollback. Re-deployment successful after secret creation. Zero order data loss.',
    engineerFeedback: 'Pre-deployment checklist must include secret verification in target namespace. Added automated check: deployment CI verifies all required secrets exist before applying.',
    createdAt: '2024-02-18T10:00:00Z',
    resolvedAt: '2024-02-18T10:06:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-006',
    title: 'API Gateway Timeout Cascade',
    service: 'api-gateway',
    environment: 'production',
    severity: 'critical',
    description: 'API gateway experiencing 45% timeout rate. All services reporting upstream failures. Gateway response times exceeding 60s. Users experiencing complete service unavailability for 30% of requests.',
    errorMessage: 'ProxyError: Upstream connect error or disconnect/reset before headers. reset reason: connection timeout. Upstream: inventory-service:8080',
    logs: '[13:10:00] WARN Gateway timeout rate: 15%\n[13:10:30] ERROR Gateway timeout rate: 45%\n[13:10:45] ERROR inventory-service: connection timeout\n[13:11:00] CRITICAL p99 latency: 61000ms\n[13:11:30] ERROR Circuit breaker OPEN for inventory-service',
    status: 'resolved',
    rootCause: 'Inventory service experienced memory leak that caused GC pauses lasting 30-60 seconds. These pauses caused the service to stop responding, causing API gateway timeouts and circuit breaker trips.',
    resolution: 'Restarted inventory service pods (immediate relief). Identified memory leak in unclosed DB cursor in product search endpoint. Deployed fix with cursor cleanup and memory profiling.',
    resolutionTimeMinutes: 31,
    failedApproaches: 'Increasing gateway timeout (masked the problem). Adding gateway replicas (not the bottleneck). Rolling back inventory service (wrong version identified initially).',
    outcome: 'API gateway timeout rate reduced to <0.1%. Memory leak fixed in inventory service. Added heap memory monitoring and automatic pod restart if heap > 80%.',
    engineerFeedback: 'Memory leaks in downstream services cause cascade failures. Added memory profiling to all services. Circuit breakers prevented complete outage - they worked as intended.',
    createdAt: '2024-03-05T13:10:00Z',
    resolvedAt: '2024-03-05T13:41:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-007',
    title: 'Message Queue Processing Delay',
    service: 'notification-service',
    environment: 'production',
    severity: 'medium',
    description: 'Notification queue lag growing exponentially. Messages delayed by 45+ minutes. Email and SMS notifications not being delivered. Queue depth at 250,000 messages. Consumer group lag increasing.',
    errorMessage: 'KafkaError: Consumer group lag: 250000 messages. Offset commit timeout: 30000ms. Consumer rebalancing detected.',
    logs: '[08:30:00] WARN Queue lag: 5000 messages\n[08:45:00] ERROR Queue lag: 50000 messages\n[09:00:00] CRITICAL Queue lag: 250000 messages\n[09:00:10] ERROR Consumer group rebalancing\n[09:15:00] ERROR Message delay: 47 minutes',
    status: 'resolved',
    rootCause: 'A consumer group rebalance storm caused by frequent pod restarts (due to liveness probe misconfiguration) kept triggering rebalances, preventing any consumer from making progress.',
    resolution: 'Fixed liveness probe thresholds (increased timeout from 5s to 30s for notification processing). Stabilized consumers. Increased consumer group parallelism from 3 to 12 consumers. Queue cleared in 15 minutes.',
    resolutionTimeMinutes: 19,
    failedApproaches: 'Increasing consumer replicas (triggered more rebalances). Resetting consumer offsets (would lose messages). Deleting and recreating consumer group (caused message duplication).',
    outcome: 'Queue lag eliminated. Notification latency back to <30 seconds. Implemented proper liveness probe configuration standards for stateful consumers.',
    engineerFeedback: 'Kafka consumers need appropriate liveness probe timeouts. Frequent rebalances completely prevent processing. Monitor consumer lag as a key SLO metric.',
    createdAt: '2024-03-12T08:30:00Z',
    resolvedAt: '2024-03-12T08:49:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-008',
    title: 'Memory Leak in Payment Service',
    service: 'payment-service',
    environment: 'production',
    severity: 'high',
    description: 'Payment service memory usage growing 50MB/hour. After 8 hours, OOMKilled by Kubernetes. Payment processing interrupted during pod restart. Heap dumps showing large number of uncollected objects.',
    errorMessage: 'OOMKilled: Container payment-service exceeded memory limit 512Mi. Node pressure: memory. Last GC: 8.4GB allocated, 7.9GB retained.',
    logs: '[00:00:00] INFO Memory: 200MB\n[04:00:00] WARN Memory: 400MB (growing)\n[06:00:00] ERROR Memory: 480MB approaching limit\n[08:05:00] ERROR OOMKilled: memory limit exceeded\n[08:05:01] INFO New pod starting (disruption)',
    status: 'resolved',
    rootCause: 'Event listener added in payment webhook handler was never removed, causing EventEmitter memory leak. Each payment request added a new listener to a global event bus without cleanup.',
    resolution: 'Identified leak via heap dump analysis (EventEmitter showing 50,000+ listeners). Fixed by using once() instead of on() for webhook events, and adding explicit listener cleanup in request lifecycle.',
    resolutionTimeMinutes: 45,
    failedApproaches: 'Increasing memory limits (just delayed the crash). Forcing GC (temporary relief only). Adding memory-based pod restart (band-aid, not a fix). Disabling event-based webhooks (broke functionality).',
    outcome: 'Memory usage stabilized at 180-200MB with zero growth over 72-hour monitoring period. Added heap memory trending alerts for early detection.',
    engineerFeedback: 'Always use once() for one-time event handlers. Added ESLint rule to flag potential EventEmitter leaks. Memory trending more valuable than threshold alerts.',
    createdAt: '2024-03-20T00:00:00Z',
    resolvedAt: '2024-03-20T00:45:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-009',
    title: 'Database Deadlock Storm',
    service: 'inventory-service',
    environment: 'production',
    severity: 'high',
    description: 'Inventory service experiencing database deadlock errors. Inventory update operations failing 35% of the time. Stock levels becoming inconsistent. Deadlock detection triggered 200+ times per minute.',
    errorMessage: 'ERROR 1213 (40001): Deadlock found when trying to get lock; try restarting transaction. Transaction: UPDATE inventory SET quantity=? WHERE product_id=? AND warehouse_id=?',
    logs: '[14:00:00] ERROR Deadlock detected: transaction rolled back\n[14:00:01] ERROR 35% of inventory updates failing\n[14:01:00] ERROR 200 deadlocks/minute\n[14:02:00] CRITICAL Inventory inconsistency detected\n[14:05:00] ERROR Order fulfillment failures: 28%',
    status: 'resolved',
    rootCause: 'Two concurrent operations updating inventory in reverse order: Order service locked product→warehouse, Restock service locked warehouse→product. Classic deadlock from inconsistent lock ordering.',
    resolution: 'Standardized lock acquisition order across all services (always: warehouse first, then product). Added SELECT FOR UPDATE with consistent ordering. Implemented retry logic with exponential backoff for deadlock errors.',
    resolutionTimeMinutes: 27,
    failedApproaches: 'Increasing transaction timeout (worsened deadlock duration). Serializable isolation (too slow, caused queue backup). Disabling concurrent updates (broke restock automation).',
    outcome: 'Deadlock rate reduced to zero. Inventory update success rate: 99.99%. Documented lock ordering standard in engineering handbook.',
    engineerFeedback: 'Lock ordering must be standardized across all services in the architecture. Deadlocks are always about ordering. Retry logic essential for any transactional system.',
    createdAt: '2024-04-02T14:00:00Z',
    resolvedAt: '2024-04-02T14:27:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-010',
    title: 'Third-Party Payment Gateway Failure',
    service: 'payment-service',
    environment: 'production',
    severity: 'medium',
    description: 'Stripe API returning 503 errors for all payment intents. Payment success rate dropped to 0%. Circuit breaker activated after 10 consecutive failures. Fallback payment processor activated.',
    errorMessage: 'StripeServiceUnavailableError: Service temporarily unavailable. Please retry your request. Status: 503. Request ID: req_stripe_incident_20240408',
    logs: '[11:20:00] ERROR Stripe 503: Service temporarily unavailable\n[11:20:10] ERROR 10 consecutive Stripe failures\n[11:20:10] INFO Circuit breaker OPEN: routing to fallback\n[11:20:11] INFO Fallback processor (Braintree) activated\n[11:24:00] INFO Stripe status: Investigating',
    status: 'resolved',
    rootCause: 'Stripe platform incident affecting payment intent creation API. External dependency failure beyond our control. Circuit breaker correctly triggered fallback to Braintree.',
    resolution: 'Circuit breaker automatically routed to Braintree fallback within 10 seconds. Monitored Stripe status page. Restored Stripe routing after their incident resolved (4 minutes total disruption).',
    resolutionTimeMinutes: 4,
    failedApproaches: 'Retrying Stripe directly (wasted time during their outage). Checking our own infrastructure (not the issue). Switching to manual payment processing (unnecessary given fallback worked).',
    outcome: 'Only 4 minutes of degraded service. Fallback processor handled all payments. Circuit breaker pattern proved its value. Zero payment failures for users.',
    engineerFeedback: 'Circuit breaker + fallback processor design worked perfectly. This incident validates our resilience architecture. Monitor third-party status pages as part of incident response.',
    createdAt: '2024-04-08T11:20:00Z',
    resolvedAt: '2024-04-08T11:24:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-011',
    title: 'Payment API Slow - Second Occurrence',
    service: 'payment-service',
    environment: 'production',
    severity: 'high',
    description: 'Payment API latency elevated again. P99 at 4500ms. Not as severe as INC-001 but same pattern emerging. Connection pool at 85% utilization. New traffic pattern from mobile app launch.',
    errorMessage: 'SlowQueryWarning: Query took 3200ms. Query: SELECT * FROM payments WHERE user_id=? ORDER BY created_at DESC. Missing index on (user_id, created_at).',
    logs: '[15:10:00] WARN p99 latency: 2100ms (baseline: 180ms)\n[15:10:30] WARN Pool utilization: 85%\n[15:11:00] ERROR p99 latency: 4500ms\n[15:11:10] WARN SlowQuery: 3200ms on payments table\n[15:11:30] WARN Pool utilization: 88%',
    status: 'resolved',
    rootCause: 'Mobile app launch increased payment history queries 5x. Missing composite index on (user_id, created_at) caused full table scans on 50M row payments table, holding DB connections longer.',
    resolution: 'Added composite index on payments(user_id, created_at DESC). Deployed in 3 minutes. Query time dropped from 3200ms to 45ms immediately. Pool utilization back to 30%.',
    resolutionTimeMinutes: 9,
    failedApproaches: 'Increasing connection pool (same mistake as INC-001, avoided this time). Caching payment history (not appropriate for financial data). Adding read replicas without fixing the query.',
    outcome: 'Payment API latency restored to <200ms p99. Learned from INC-001 to check query performance first before scaling resources.',
    engineerFeedback: 'Pattern recognition from INC-001 helped diagnose faster. DB query analysis should be first step for latency issues, not resource scaling.',
    createdAt: '2024-04-15T15:10:00Z',
    resolvedAt: '2024-04-15T15:19:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-012',
    title: 'Kubernetes Pod OOM Kill Loop',
    service: 'ml-inference-service',
    environment: 'production',
    severity: 'high',
    description: 'ML inference service pods continuously OOMKilled. Model serving unavailable. Product recommendation API returning 503. Five pod restarts in 30 minutes. Model loaded fresh on each restart causing 2-minute warmup gaps.',
    errorMessage: 'OOMKilled: Container ml-inference exceeded memory limit 1Gi. Node memory pressure: Critical. Model size: 850MB, runtime overhead: 300MB, peak batch: 400MB.',
    logs: '[09:00:00] INFO Pod restart #1 - OOMKilled\n[09:02:00] INFO Model loading... (2 min warmup)\n[09:08:00] ERROR Pod restart #2 - OOMKilled during batch\n[09:10:00] INFO Model loading again\n[09:25:00] CRITICAL 5 restarts in 30 minutes',
    status: 'resolved',
    rootCause: 'ML model memory requirements were underestimated. Model (850MB) + runtime (300MB) + peak batch processing memory (400MB) = 1550MB exceeded 1GB limit. Limit set based on idle memory, not peak.',
    resolution: 'Increased memory limit to 2.5GB with request of 2GB. Added model caching to prevent reload on restart. Implemented batch size limits to cap peak memory at 200MB.',
    resolutionTimeMinutes: 15,
    failedApproaches: 'Reducing batch concurrency (still OOM during normal load). Enabling memory compression (Kubernetes overhead too high). Vertical pod autoscaling (too slow to respond to OOM).',
    outcome: 'ML inference service stable for 30+ days. Memory usage: 1.4GB steady state, 1.8GB peak. Recommendations API at 99.9% availability.',
    engineerFeedback: 'Memory limits must account for peak usage, not average. Profile memory under load before setting limits. ML services need extra headroom for model + runtime + batch overhead.',
    createdAt: '2024-05-01T09:00:00Z',
    resolvedAt: '2024-05-01T09:15:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-013',
    title: 'SSL Certificate Expiry',
    service: 'api-gateway',
    environment: 'production',
    severity: 'critical',
    description: 'SSL certificate for api.incidentmind.com expired at midnight UTC. All HTTPS connections failing. Browsers showing ERR_CERT_DATE_INVALID. 100% of API traffic affected. Certificate expiry alert was misconfigured.',
    errorMessage: 'SSL_ERROR_RX_RECORD_TOO_LONG: Certificate for api.incidentmind.com expired at 2024-06-01T00:00:00Z. Certificate CN=api.incidentmind.com, validity: 2023-06-01 to 2024-06-01.',
    logs: '[00:00:01] CRITICAL SSL certificate expired: api.incidentmind.com\n[00:00:01] ERROR All HTTPS connections rejected\n[00:00:02] CRITICAL Traffic: 0 requests/second (down from 450 rps)\n[00:01:00] PAGERDUTY Certificate expiry alert triggered\n[00:02:00] INFO Engineer on-call notified',
    status: 'resolved',
    rootCause: 'SSL certificate renewed manually last year. Auto-renewal was configured but failed silently when the certificate authority changed their ACME challenge requirements. Expiry monitoring alert had wrong email address.',
    resolution: 'Emergency cert renewal using Let\'s Encrypt with updated ACME configuration. Deployed new cert in 3 minutes. Re-enabled auto-renewal with correct configuration and alerting.',
    resolutionTimeMinutes: 3,
    failedApproaches: 'Using expired cert with SSL_VERIFY_NONE (security risk, rejected). Self-signed cert (browser warnings). Waiting for auto-renewal (already failed, would not self-heal).',
    outcome: 'HTTPS restored in 3 minutes. Auto-renewal now tested monthly. Added 30-day, 14-day, 7-day, and 1-day expiry alerts to separate monitoring system.',
    engineerFeedback: 'Certificate auto-renewal must be actively monitored and tested, not assumed. Added cert expiry check to synthetic monitoring. Never rely on a single alerting path for critical infrastructure.',
    createdAt: '2024-06-01T00:00:00Z',
    resolvedAt: '2024-06-01T00:03:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-014',
    title: 'Payment API Latency - Third Occurrence',
    service: 'payment-service',
    environment: 'production',
    severity: 'critical',
    description: 'Third occurrence of payment API latency. This time P99 at 12000ms - worse than before. Connection pool exhaustion AND query slowness occurring simultaneously. Black Friday traffic (8x normal).',
    errorMessage: 'MULTIPLE: PoolError: Connection pool exhausted (50/50). SlowQueryWarning: 7800ms on payment_methods table. Throughput collapsed from 2000 rps to 180 rps.',
    logs: '[00:01:00] WARN Black Friday: 8x normal traffic\n[00:01:30] ERROR Pool exhausted: 50/50 connections\n[00:01:31] ERROR SlowQuery: 7800ms on payment_methods\n[00:02:00] CRITICAL p99 latency: 12000ms\n[00:02:30] CRITICAL Payment success rate: 12%',
    status: 'resolved',
    rootCause: 'Combined failure: (1) Connection pool still too small for 8x traffic even after INC-001 fix. (2) Missing index on payment_methods(user_id, status) discovered under high load. (3) No read replica for payment history queries.',
    resolution: 'Applied connection pool emergency increase. Added missing index (online index build, 2 min). Enabled read replica for read-only payment queries. Rate limited payment history API during incident.',
    resolutionTimeMinutes: 17,
    failedApproaches: 'Disabling payment history (complex to do safely). Adding more pool connections without index fix (no improvement). Emergency pod scaling (hit DB connection ceiling immediately).',
    outcome: 'Payment success rate restored to 99.7%. Implemented comprehensive payment service capacity plan. Connection pool autoscaling added. Three indexes added proactively.',
    engineerFeedback: 'Recurring incidents signal systemic architecture issues. Payment service needs comprehensive load testing against 10x traffic. Read/write splitting should have been done after INC-011.',
    createdAt: '2024-11-29T00:01:00Z',
    resolvedAt: '2024-11-29T00:18:00Z',
    hindsightStored: true
  },
  {
    id: 'INC-015',
    title: 'CDN Cache Poisoning Attack',
    service: 'cdn',
    environment: 'production',
    severity: 'critical',
    description: 'CDN serving malicious cached responses to users. Attacker exploited cache key normalization vulnerability to cache a poisoned response. Users receiving modified JavaScript files. Security team alerted by XSS detection.',
    errorMessage: 'SecurityAlert: XSS attempt detected in cached CDN response. Cache key collision detected: /static/app.js?utm_source=evil vs /static/app.js. Malicious script injected in cached response.',
    logs: '[16:30:00] SECURITY XSS payload detected in CDN response\n[16:30:01] SECURITY Cache poisoning: /static/app.js compromised\n[16:30:02] CRITICAL Malicious JS served to 2400 users\n[16:30:10] SECURITY CDN cache poisoning confirmed\n[16:31:00] INCIDENT Security team paged',
    status: 'resolved',
    rootCause: 'CDN cache key did not normalize URL parameters. Attacker crafted request with query parameter that was not part of cache key, causing poisoned response to be cached and served to all users of that URL.',
    resolution: 'Immediate full CDN cache purge (2 minutes). Deployed cache key normalization to include all URL parameters. Added Vary headers. Implemented CSP headers. Rotated CDN configuration.',
    resolutionTimeMinutes: 22,
    failedApproaches: 'Partial cache purge by path (missed some poisoned entries). Temporarily disabling CDN (caused origin overload). Blocking by user agent (attacker changed UA).',
    outcome: 'Cache poisoning eliminated. Full cache purge took 2 minutes. Implemented WAF rules for cache poisoning patterns. Added integrity verification for all static assets.',
    engineerFeedback: 'CDN cache keys must include all URL parameters or use explicit allow-list. Added cache poisoning to security review checklist. Incident response for security events needs separate playbook.',
    createdAt: '2024-08-14T16:30:00Z',
    resolvedAt: '2024-08-14T16:52:00Z',
    hindsightStored: true
  }
];
